// Package testvectors verifies that the Go implementation produces
// byte-for-byte identical output to the published AAFP test vectors.
//
// This is the primary interoperability validation. If all vectors pass,
// the Go implementation produces canonical wire format compatible with
// the Rust reference implementation.
//
// Test vectors are from TEST_VECTORS.md, generated by the Rust implementation.
// The Go implementation was written from the RFCs alone and must reproduce
// each vector without consulting the Rust source.
package testvectors

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"testing"

	"aafp-go/cbor"
	aafperrors "aafp-go/errors"
	"aafp-go/frame"
	"aafp-go/handshake"
	"aafp-go/identity"
)

// Fixed test inputs from TEST_VECTORS.md
var (
	agentIDA     = bytes32(0x01)
	agentIDB     = bytes32(0x02)
	nonceA       = bytes32(0x03)
	nonceB       = bytes32(0x04)
	tlsBinding   = bytes32(0x05)
	sessionID    = bytes32(0x06)
	publicKeyA   = bytesN(0x42, 1952)
	publicKeyB   = bytesN(0x43, 1952)
	signatureA   = bytesN(0x44, 3309)
	signatureB   = bytesN(0x45, 3309)
	timestampNow = uint64(1735689600)
	timestampExp = uint64(1736294400)
)

func bytes32(b byte) []byte {
	v := make([]byte, 32)
	for i := range v {
		v[i] = b
	}
	return v
}

func bytesN(b byte, n int) []byte {
	v := make([]byte, n)
	for i := range v {
		v[i] = b
	}
	return v
}

func hexHash(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}

// mustEncode encodes a CBOR value and returns its hex representation.
func mustEncode(t *testing.T, v cbor.Value) string {
	b, err := cbor.Encode(&v)
	if err != nil {
		t.Fatalf("CBOR encode failed: %v", err)
	}
	return hex.EncodeToString(b)
}

func mustEncodeBytes(t *testing.T, v cbor.Value) []byte {
	b, err := cbor.Encode(&v)
	if err != nil {
		t.Fatalf("CBOR encode failed: %v", err)
	}
	return b
}

// === CBOR Canonical Encoding ===

func TestCBORUnsignedSmall(t *testing.T) {
	got := mustEncode(t, cbor.UUint(5))
	want := "05"
	if got != want {
		t.Errorf("uint 5: got %s, want %s", got, want)
	}
}

func TestCBORUnsigned24(t *testing.T) {
	got := mustEncode(t, cbor.UUint(24))
	want := "1818"
	if got != want {
		t.Errorf("uint 24: got %s, want %s", got, want)
	}
}

func TestCBORUnsigned100(t *testing.T) {
	got := mustEncode(t, cbor.UUint(100))
	want := "1864"
	if got != want {
		t.Errorf("uint 100: got %s, want %s", got, want)
	}
}

func TestCBORUnsigned1000(t *testing.T) {
	got := mustEncode(t, cbor.UUint(1000))
	want := "1903e8"
	if got != want {
		t.Errorf("uint 1000: got %s, want %s", got, want)
	}
}

func TestCBORNegative1(t *testing.T) {
	got := mustEncode(t, cbor.NInt(-1))
	want := "20"
	if got != want {
		t.Errorf("int -1: got %s, want %s", got, want)
	}
}

func TestCBORNegative100(t *testing.T) {
	got := mustEncode(t, cbor.NInt(-100))
	want := "3863"
	if got != want {
		t.Errorf("int -100: got %s, want %s", got, want)
	}
}

func TestCBORBoolTrue(t *testing.T) {
	got := mustEncode(t, cbor.Bool(true))
	want := "f5"
	if got != want {
		t.Errorf("bool true: got %s, want %s", got, want)
	}
}

func TestCBORBoolFalse(t *testing.T) {
	got := mustEncode(t, cbor.Bool(false))
	want := "f4"
	if got != want {
		t.Errorf("bool false: got %s, want %s", got, want)
	}
}

func TestCBORNull(t *testing.T) {
	got := mustEncode(t, cbor.Null())
	want := "f6"
	if got != want {
		t.Errorf("null: got %s, want %s", got, want)
	}
}

func TestCBORByteString32(t *testing.T) {
	got := mustEncode(t, cbor.BStr(bytes32(0xaa)))
	want := "5820aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	if got != want {
		t.Errorf("bstr32: got %s, want %s", got, want)
	}
}

func TestCBORTextString(t *testing.T) {
	got := mustEncode(t, cbor.TStr("hello"))
	want := "6568656c6c6f"
	if got != want {
		t.Errorf("tstr: got %s, want %s", got, want)
	}
}

func TestCBOREmptyArray(t *testing.T) {
	got := mustEncode(t, cbor.Arr([]cbor.Value{}))
	want := "80"
	if got != want {
		t.Errorf("empty array: got %s, want %s", got, want)
	}
}

func TestCBOREmptyIntMap(t *testing.T) {
	got := mustEncode(t, cbor.IMap([]cbor.IntMapEntry{}))
	want := "a0"
	if got != want {
		t.Errorf("empty map: got %s, want %s", got, want)
	}
}

func TestCBORIntMapSorted(t *testing.T) {
	// {1: "a", 100: "b"} — key 1 (1 byte) before key 100 (2 bytes)
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.TStr("a")},
		{Key: 100, Value: cbor.TStr("b")},
	})
	got := mustEncode(t, v)
	want := "a201616118646162"
	if got != want {
		t.Errorf("int map sorted: got %s, want %s", got, want)
	}
}

func TestCBORIntMapSameLength(t *testing.T) {
	// {10: 1, 20: 2} — same-length keys sorted bytewise
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 10, Value: cbor.UUint(1)},
		{Key: 20, Value: cbor.UUint(2)},
	})
	got := mustEncode(t, v)
	want := "a20a011402"
	if got != want {
		t.Errorf("int map same-length: got %s, want %s", got, want)
	}
}

func TestCBORStrMapSorted(t *testing.T) {
	// {"cat": 1, "apple": 2, "zebra": 3} — length-first
	v := cbor.SMap([]cbor.StrMapEntry{
		{Key: "cat", Value: cbor.UUint(1)},
		{Key: "apple", Value: cbor.UUint(2)},
		{Key: "zebra", Value: cbor.UUint(3)},
	})
	got := mustEncode(t, v)
	want := "a36363617401656170706c6502657a6562726103"
	if got != want {
		t.Errorf("str map sorted: got %s, want %s", got, want)
	}
}

// === Frame Wire Format ===

func TestFrameDataEmpty(t *testing.T) {
	f := &frame.Frame{
		Version:   frame.Version,
		FrameType: frame.TypeData,
		StreamID:  0,
	}
	b, err := frame.Encode(f)
	if err != nil {
		t.Fatal(err)
	}
	got := hex.EncodeToString(b)
	want := "01010000000000000000000000000000000000000000000000000000"
	if got != want {
		t.Errorf("frame data empty: got %s, want %s", got, want)
	}
}

func TestFrameDataStream42(t *testing.T) {
	f := &frame.Frame{
		Version:   frame.Version,
		FrameType: frame.TypeData,
		StreamID:  42,
		Payload:   []byte{0xde, 0xad, 0xbe, 0xef},
	}
	b, err := frame.Encode(f)
	if err != nil {
		t.Fatal(err)
	}
	got := hex.EncodeToString(b)
	want := "01010000000000000000002a00000000000000040000000000000000deadbeef"
	if got != want {
		t.Errorf("frame data stream42: got %s, want %s", got, want)
	}
}

func TestFrameHandshake(t *testing.T) {
	f := &frame.Frame{
		Version:   frame.Version,
		FrameType: frame.TypeHandshake,
		StreamID:  0,
		Payload:   []byte{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08},
	}
	b, err := frame.Encode(f)
	if err != nil {
		t.Fatal(err)
	}
	got := hex.EncodeToString(b)
	want := "010200000000000000000000000000000000000800000000000000000102030405060708"
	if got != want {
		t.Errorf("frame handshake: got %s, want %s", got, want)
	}
}

func TestFrameRPCRequest(t *testing.T) {
	f := &frame.Frame{
		Version:   frame.Version,
		FrameType: frame.TypeRPCRequest,
		StreamID:  4,
		Payload:   []byte{0xa1, 0x01, 0x02},
	}
	b, err := frame.Encode(f)
	if err != nil {
		t.Fatal(err)
	}
	got := hex.EncodeToString(b)
	want := "01030000000000000000000400000000000000030000000000000000a10102"
	if got != want {
		t.Errorf("frame rpc request: got %s, want %s", got, want)
	}
}

func TestFramePing(t *testing.T) {
	f := &frame.Frame{
		Version:   frame.Version,
		FrameType: frame.TypePing,
		StreamID:  0,
	}
	b, err := frame.Encode(f)
	if err != nil {
		t.Fatal(err)
	}
	got := hex.EncodeToString(b)
	want := "01070000000000000000000000000000000000000000000000000000"
	if got != want {
		t.Errorf("frame ping: got %s, want %s", got, want)
	}
}

func TestFrameDataFlagsMore(t *testing.T) {
	f := &frame.Frame{
		Version:   frame.Version,
		FrameType: frame.TypeData,
		Flags:     frame.FlagMore,
		StreamID:  8,
		Payload:   []byte{0xff},
	}
	b, err := frame.Encode(f)
	if err != nil {
		t.Fatal(err)
	}
	got := hex.EncodeToString(b)
	want := "01010100000000000000000800000000000000010000000000000000ff"
	if got != want {
		t.Errorf("frame more flag: got %s, want %s", got, want)
	}
}

// === Handshake Structures ===

func TestHandshakeClientHelloWithoutSig(t *testing.T) {
	ch := &handshake.ClientHello{
		ProtocolVersion: 1,
		AgentId:         agentIDA,
		PublicKey:       publicKeyA,
		Nonce:           nonceA,
		Capabilities:    []cbor.Value{},
		Extensions:      []handshake.ExtensionEntry{},
		ExpiresAt:       timestampExp,
		KeyAlgorithm:    1,
	}
	cborVal := ch.ToCBORWithoutSigAndMac()
	b := mustEncodeBytes(t, cborVal)
	gotHash := hexHash(b)
	wantHash := "ac5bb0f3107963c9c2c6850f59323cd1f9b3666832d439010410e8115a98d0dc"
	if gotHash != wantHash {
		t.Errorf("ClientHello without sig:\n  got  hash: %s\n  want hash: %s\n  got  bytes: %s",
			gotHash, wantHash, hex.EncodeToString(b))
	}
}

func TestHandshakeServerHelloWithoutSig(t *testing.T) {
	sh := &handshake.ServerHello{
		ProtocolVersion: 1,
		AgentId:         agentIDB,
		PublicKey:       publicKeyB,
		Nonce:           nonceB,
		Capabilities:    []cbor.Value{},
		Extensions:      []handshake.ExtensionEntry{},
		SessionId:       sessionID,
		ExpiresAt:       timestampExp,
		KeyAlgorithm:    1,
	}
	cborVal := sh.ToCBORWithoutSig()
	b := mustEncodeBytes(t, cborVal)
	gotHash := hexHash(b)
	wantHash := "2989d7fcb02f566e3f0446b42a6819f10b5f326e7c4de28eec0eab988f47631e"
	if gotHash != wantHash {
		t.Errorf("ServerHello without sig:\n  got  hash: %s\n  want hash: %s",
			gotHash, wantHash)
	}
}

func TestHandshakeClientFinishedWithoutSig(t *testing.T) {
	cf := &handshake.ClientFinished{
		SessionId: sessionID,
	}
	cborVal := cf.ToCBORWithoutSig()
	b := mustEncodeBytes(t, cborVal)
	gotHash := hexHash(b)
	wantHash := "5a0feb1c90f3e6f0ad82064db1337e2699ad3f50f1e88df31736b0b441e1290d"
	if gotHash != wantHash {
		t.Errorf("ClientFinished without sig:\n  got  hash: %s\n  want hash: %s",
			gotHash, wantHash)
	}
}

func TestTranscriptHashInit(t *testing.T) {
	th := handshake.NewTranscriptHash(tlsBinding)
	got := hex.EncodeToString(th.Current())
	want := "f849d67325facf04177bc663b2dc544051831c589ef581d412f2eba44834e77c"
	if got != want {
		t.Errorf("transcript hash init:\n  got  %s\n  want %s", got, want)
	}
}

// === AgentRecord ===

func TestAgentIdFromFixedPubkey(t *testing.T) {
	id := identity.AgentIdFromPubkey(publicKeyA)
	got := hex.EncodeToString(id)
	want := "587a1e4a37aa6c5a79b48fcc47d3b937a732ef9248ab15b56360a80b085ce5cc"
	if got != want {
		t.Errorf("agent_id from pubkey:\n  got  %s\n  want %s", got, want)
	}
}

func TestAgentRecordWithoutSig(t *testing.T) {
	r := &identity.AgentRecord{
		RecordType: identity.RecordTypeV1,
		AgentId:    identity.AgentIdFromPubkey(publicKeyA),
		PublicKey:  publicKeyA,
		Capabilities: []identity.CapabilityDescriptor{
			{
				Name: "inference",
				Metadata: map[string]cbor.Value{
					"model": cbor.TStr("test-model"),
				},
			},
		},
		Endpoints:    []string{"/ip4/127.0.0.1/tcp/4001"},
		CreatedAt:    timestampNow,
		ExpiresAt:    timestampExp,
		KeyAlgorithm: identity.KeyAlgMLDSA65,
	}
	cborVal := r.ToCBORWithoutSig()
	b := mustEncodeBytes(t, cborVal)
	gotHash := hexHash(b)
	wantHash := "75dba7094f64999fc9681192099a54810f73a5a52c99dd9106574469f9a5e280"
	if gotHash != wantHash {
		t.Errorf("AgentRecord without sig:\n  got  hash: %s\n  want hash: %s\n  got  bytes: %s",
			gotHash, wantHash, hex.EncodeToString(b[:80]))
	}
}

func TestAgentRecordEmptyCapabilities(t *testing.T) {
	// Uses pubkey B (0x43)
	r := &identity.AgentRecord{
		RecordType:   identity.RecordTypeV1,
		AgentId:      identity.AgentIdFromPubkey(publicKeyB),
		PublicKey:    publicKeyB,
		Capabilities: []identity.CapabilityDescriptor{},
		Endpoints:    []string{},
		CreatedAt:    timestampNow,
		ExpiresAt:    timestampExp,
		KeyAlgorithm: identity.KeyAlgMLDSA65,
	}
	cborVal := r.ToCBORWithoutSig()
	b := mustEncodeBytes(t, cborVal)
	gotHash := hexHash(b)
	wantHash := "c9466f89e50207add067399faa81e9e8b7110b33c92bbc9234e916e1fe79aec2"
	if gotHash != wantHash {
		t.Errorf("AgentRecord empty caps:\n  got  hash: %s\n  want hash: %s",
			gotHash, wantHash)
	}
}

// === RPC Messages ===

func TestRPCRequestBasic(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(1)},
		{Key: 2, Value: cbor.TStr("aafp.discovery.lookup")},
		{Key: 3, Value: cbor.Null()},
	})
	got := mustEncode(t, v)
	want := "a301010275616166702e646973636f766572792e6c6f6f6b757003f6"
	if got != want {
		t.Errorf("rpc request basic: got %s, want %s", got, want)
	}
}

func TestRPCRequestWithParams(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(42)},
		{Key: 2, Value: cbor.TStr("aafp.discovery.lookup")},
		{Key: 3, Value: cbor.TStr("inference")},
	})
	got := mustEncode(t, v)
	want := "a301182a0275616166702e646973636f766572792e6c6f6f6b75700369696e666572656e6365"
	if got != want {
		t.Errorf("rpc request with params: got %s, want %s", got, want)
	}
}

func TestRPCResponseSuccess(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(42)},
		{Key: 2, Value: cbor.UUint(100)},
		{Key: 3, Value: cbor.Null()},
	})
	got := mustEncode(t, v)
	want := "a301182a02186403f6"
	if got != want {
		t.Errorf("rpc response success: got %s, want %s", got, want)
	}
}

func TestRPCResponseError(t *testing.T) {
	errObj := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(4005)},
		{Key: 2, Value: cbor.TStr("not found")},
		{Key: 3, Value: cbor.Null()},
	})
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(42)},
		{Key: 2, Value: cbor.Null()},
		{Key: 3, Value: errObj},
	})
	got := mustEncode(t, v)
	want := "a301182a02f603a301190fa502696e6f7420666f756e6403f6"
	if got != want {
		t.Errorf("rpc response error: got %s, want %s", got, want)
	}
}

func TestCloseMessage(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(0)},
		{Key: 2, Value: cbor.TStr("goodbye")},
	})
	got := mustEncode(t, v)
	want := "a201000267676f6f64627965"
	if got != want {
		t.Errorf("close message: got %s, want %s", got, want)
	}
}

func TestErrorMessageFatal(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(2001)},
		{Key: 2, Value: cbor.TStr("invalid signature")},
		{Key: 3, Value: cbor.Null()},
		{Key: 4, Value: cbor.Bool(true)},
	})
	got := mustEncode(t, v)
	want := "a4011907d10271696e76616c6964207369676e617475726503f604f5"
	if got != want {
		t.Errorf("error message fatal: got %s, want %s", got, want)
	}
}

// === Discovery ===

func TestDiscoveryLookupParams(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.TStr("inference")},
		{Key: 2, Value: cbor.UUint(10)},
	})
	got := mustEncode(t, v)
	want := "a20169696e666572656e6365020a"
	if got != want {
		t.Errorf("lookup params: got %s, want %s", got, want)
	}
}

func TestDiscoveryLookupParamsNullLimit(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.TStr("inference")},
		{Key: 2, Value: cbor.Null()},
	})
	got := mustEncode(t, v)
	want := "a20169696e666572656e636502f6"
	if got != want {
		t.Errorf("lookup params null: got %s, want %s", got, want)
	}
}

func TestDiscoveryAnnounceResultEmpty(t *testing.T) {
	v := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.Arr([]cbor.Value{})},
	})
	got := mustEncode(t, v)
	want := "a10180"
	if got != want {
		t.Errorf("announce result empty: got %s, want %s", got, want)
	}
}

func TestDiscoveryAnnounceParams(t *testing.T) {
	// Announce params: {1: AgentRecord}
	// AgentRecord has capability "inference" (no metadata), endpoint, and signature A
	r := &identity.AgentRecord{
		RecordType: identity.RecordTypeV1,
		AgentId:    identity.AgentIdFromPubkey(publicKeyA),
		PublicKey:  publicKeyA,
		Capabilities: []identity.CapabilityDescriptor{
			{Name: "inference"},
		},
		Endpoints:    []string{"/ip4/127.0.0.1/tcp/4001"},
		CreatedAt:    timestampNow,
		ExpiresAt:    timestampExp,
		Signature:    signatureA,
		KeyAlgorithm: identity.KeyAlgMLDSA65,
	}
	recordCBOR := r.ToCBOR()
	params := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: recordCBOR},
	})
	b := mustEncodeBytes(t, params)
	gotHash := hexHash(b)
	wantHash := "7dbdeddac0729c9734204c454b711c1a43762d02157385e53f7b0e0e0794ed40"
	if gotHash != wantHash {
		t.Errorf("announce params:\n  got  hash: %s\n  want hash: %s",
			gotHash, wantHash)
	}
}

// === Round-trip tests ===

func TestCBORRoundTrip(t *testing.T) {
	original := cbor.IMap([]cbor.IntMapEntry{
		{Key: 1, Value: cbor.UUint(42)},
		{Key: 2, Value: cbor.TStr("hello")},
		{Key: 100, Value: cbor.BStr([]byte{1, 2, 3})},
	})
	encoded, err := cbor.Encode(&original)
	if err != nil {
		t.Fatal(err)
	}
	decoded, n, err := cbor.Decode(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if n != len(encoded) {
		t.Errorf("round-trip: consumed %d, expected %d", n, len(encoded))
	}
	if decoded.Kind() != cbor.KindIntMap {
		t.Fatalf("round-trip: expected int map, got %d", decoded.Kind())
	}
	if v := decoded.IntMapGet(1); v == nil || v.Uint() != 42 {
		t.Error("round-trip: key 1 mismatch")
	}
	if v := decoded.IntMapGet(2); v == nil || v.Str() != "hello" {
		t.Error("round-trip: key 2 mismatch")
	}
}

func TestFrameRoundTrip(t *testing.T) {
	original := &frame.Frame{
		Version:    frame.Version,
		FrameType:  frame.TypeData,
		Flags:      frame.FlagMore,
		StreamID:   42,
		Extensions: []byte{0xaa, 0xbb},
		Payload:    []byte{0xde, 0xad, 0xbe, 0xef},
	}
	encoded, err := frame.Encode(original)
	if err != nil {
		t.Fatal(err)
	}
	decoded, n, err := frame.Decode(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if n != len(encoded) {
		t.Errorf("round-trip: consumed %d, expected %d", n, len(encoded))
	}
	if decoded.StreamID != 42 {
		t.Errorf("round-trip: stream ID %d, expected 42", decoded.StreamID)
	}
	if decoded.Flags != frame.FlagMore {
		t.Errorf("round-trip: flags 0x%02x, expected 0x%02x", decoded.Flags, frame.FlagMore)
	}
}

// === Negative tests ===

func TestFrameRejectOversizedPayload(t *testing.T) {
	// Frame with payload length > MaxPayloadSize should be rejected
	header := make([]byte, frame.HeaderSize)
	header[0] = frame.Version
	header[1] = frame.TypeData
	// Set payload length to MaxPayloadSize + 1
	binary.BigEndian.PutUint64(header[12:20], uint64(frame.MaxPayloadSize+1))
	_, _, err := frame.Decode(header)
	if err == nil {
		t.Error("should reject oversized payload")
	}
}

func TestFrameRejectOverflow(t *testing.T) {
	// Frame with ext_len + payload_len that overflows uint64
	header := make([]byte, frame.HeaderSize)
	header[0] = frame.Version
	header[1] = frame.TypeData
	binary.BigEndian.PutUint64(header[12:20], ^uint64(0)) // max payload
	binary.BigEndian.PutUint64(header[20:28], 1)          // 1 byte ext
	_, _, err := frame.Decode(header)
	if err == nil {
		t.Error("should reject length overflow")
	}
}

func TestFrameRejectBadVersion(t *testing.T) {
	header := make([]byte, frame.HeaderSize)
	header[0] = 2 // wrong version
	header[1] = frame.TypeData
	_, _, err := frame.Decode(header)
	if err == nil {
		t.Error("should reject bad version")
	}
}

func TestCBORRejectTruncated(t *testing.T) {
	// Truncated byte string: claims 32 bytes but only has 5
	data := []byte{0x58, 0x20, 0x01, 0x02, 0x03, 0x04, 0x05}
	_, _, err := cbor.Decode(data)
	if err == nil {
		t.Error("should reject truncated byte string")
	}
}

func TestCBORRejectHugeArray(t *testing.T) {
	// Array claiming 0xFFFFFFFF items but with no data
	data := []byte{0x9a, 0xff, 0xff, 0xff, 0xff}
	_, _, err := cbor.Decode(data)
	if err == nil {
		t.Error("should reject huge array with no data")
	}
}

// === Error code tests ===

func TestErrorCodesAlwaysFatal(t *testing.T) {
	fatalCodes := []uint32{2001, 2002, 2006, 2007, 8004, 8005, 8006, 8009}
	for _, code := range fatalCodes {
		if !aafperrors.IsAlwaysFatal(code) {
			t.Errorf("code %d should be always fatal", code)
		}
	}
	nonFatalCodes := []uint32{0, 1001, 4001, 5001, 8001, 9000}
	for _, code := range nonFatalCodes {
		if aafperrors.IsAlwaysFatal(code) {
			t.Errorf("code %d should NOT be always fatal", code)
		}
	}
}

// === Session ID derivation ===

func TestSessionIdDerivation(t *testing.T) {
	// Verify the session ID derivation is deterministic
	h := bytes32(0xaa) // placeholder transcript hash
	sid := handshake.ComputeSessionId(h, nonceA, nonceB, agentIDB)
	if len(sid) != 32 {
		t.Errorf("session ID length: %d, expected 32", len(sid))
	}
	// Same inputs must produce same output
	sid2 := handshake.ComputeSessionId(h, nonceA, nonceB, agentIDB)
	if string(sid) != string(sid2) {
		t.Error("session ID derivation is not deterministic")
	}
	// Different inputs must produce different output
	sid3 := handshake.ComputeSessionId(h, nonceB, nonceA, agentIDB)
	if string(sid) == string(sid3) {
		t.Error("session ID should differ when nonce order changes")
	}
}
